import { StatusBadge } from "@/components/ui/surface";
import type { Obligation, OrganizationUser } from "@/lib/api";
import type { ObligationDetailDraft } from "./use-obligation-detail";

const labels = { PENDING: "Pendiente", IN_PROGRESS: "En proceso", COMPLIANT: "Cumplida", OVERDUE: "Vencida" };
const tones = { PENDING: "warning", IN_PROGRESS: "info", COMPLIANT: "success", OVERDUE: "danger" } as const;
const statuses: Obligation["compliance_status"][] = ["PENDING", "IN_PROGRESS", "COMPLIANT", "OVERDUE"];
const inputClass = "control-field h-10 w-full rounded-[9px] border px-3 text-sm text-slate-800 outline-none transition";
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-1.5 block text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</span>{children}</label>; }

export function ObligationDetailFields({ obligation, users, draft, change, editable, canAssign, saving }: { obligation: Obligation; users: OrganizationUser[]; draft: ObligationDetailDraft; change: <K extends keyof ObligationDetailDraft>(field: K, value: ObligationDetailDraft[K]) => void; editable: boolean; canAssign: boolean; saving: boolean }) {
  const responsible = obligation.responsible_user?.name ?? users.find((user) => user.id === obligation.responsible_user_id)?.name ?? "Sin responsable";
  return <section className="grid gap-x-4 gap-y-3 border-b border-slate-200/90 pb-5 sm:grid-cols-2"><Field label="Responsable">{editable && canAssign ? <select aria-label="Responsable" className={inputClass} disabled={saving} onChange={(event) => change("responsible_user_id", event.target.value || null)} value={draft.responsible_user_id ?? ""}><option value="">Sin responsable</option>{users.filter((user) => user.is_active && (user.role === "ADMIN" || user.role === "RESPONSIBLE")).map((user) => <option key={user.id} value={user.id}>{user.name}</option>)}</select> : <p className="flex h-10 items-center rounded-[9px] border border-transparent bg-slate-50 px-3 text-sm text-slate-700">{responsible}</p>}</Field><Field label="Estado">{editable ? <select aria-label="Estado" className={inputClass} disabled={saving} onChange={(event) => change("compliance_status", event.target.value as Obligation["compliance_status"])} value={draft.compliance_status}>{statuses.map((status) => <option key={status} value={status}>{labels[status]}</option>)}</select> : <div className="flex h-10 items-center"><StatusBadge tone={tones[obligation.compliance_status]}>{labels[obligation.compliance_status]}</StatusBadge></div>}</Field><Field label="Fecha límite">{editable ? <input aria-label="Fecha límite" className={inputClass} disabled={saving} onChange={(event) => change("deadline", event.target.value)} type="date" value={draft.deadline} /> : <p className="flex h-10 items-center rounded-[9px] border border-transparent bg-slate-50 px-3 text-sm text-slate-700">{obligation.deadline ?? "Sin fecha"}</p>}</Field><Field label="Frecuencia">{editable ? <input aria-label="Frecuencia" className={inputClass} disabled={saving} onChange={(event) => change("frequency", event.target.value)} placeholder="Ej. Anual" value={draft.frequency} /> : <p className="flex h-10 items-center rounded-[9px] border border-transparent bg-slate-50 px-3 text-sm text-slate-700">{obligation.frequency ?? "No definida"}</p>}</Field></section>;
}
