"use client";

import { useEffect, useState } from "react";
import { DashboardGate } from "@/components/auth/dashboard-gate";
import { Card, EmptyState, PageHeader } from "@/components/ui/surface";
import { PrimaryButton } from "@/components/ui/primary-button";
import { TextField } from "@/components/ui/text-field";
import { analyzeCompanyProfile, analyzeDocument, getCurrentUser, updateCompanyProfile, type CompanyProfileExtraction, type CompanyType, type OrganizationProposal } from "@/lib/api";

const MAX_DOCUMENT_LENGTH = 20_000;
const companyLabels: Record<CompanyType, string> = { SPA: "SpA", LIMITADA: "Limitada", SA_CERRADA: "S.A. Cerrada", SA_ABIERTA: "S.A. Abierta", EIRL: "EIRL", OTHER: "Otro", UNKNOWN: "No identificado" };

export default function DocumentAnalysisPage() {
  const [mode, setMode] = useState<"organization" | "company">("organization");
  const [text, setText] = useState(""); const [file, setFile] = useState<File | null>(null); const [organization, setOrganization] = useState<OrganizationProposal | null>(null); const [company, setCompany] = useState<CompanyProfileExtraction | null>(null); const [allowed, setAllowed] = useState<boolean | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false);
  useEffect(() => { getCurrentUser().then((user) => setAllowed(user.role === "ADMIN")).catch(() => setAllowed(false)); }, []);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); setOrganization(null); setCompany(null); try { if (mode === "organization") setOrganization(await analyzeDocument(text)); else { if (!file) throw new Error("Selecciona un PDF con capa de texto."); setCompany(await analyzeCompanyProfile(file)); setFile(null); } } catch (caught) { setError(caught instanceof Error ? caught.message : "No fue posible analizar el documento."); } finally { setLoading(false); } }
  async function applyCompany(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!company) return; const form = new FormData(event.currentTarget); setSaving(true); setError(""); try { await updateCompanyProfile({ name: String(form.get("name")), rut: String(form.get("rut")), company_type: form.get("company_type") as CompanyType, business_purpose: String(form.get("business_purpose") || "") || null, address: String(form.get("address") || "") || null }); setCompany(null); } catch (caught) { setError(caught instanceof Error ? caught.message : "No fue posible actualizar el perfil."); } finally { setSaving(false); } }
  return <DashboardGate>{allowed === false ? <EmptyState title="Acceso restringido" description="Solo los administradores pueden analizar documentos." /> : <div className="max-w-4xl space-y-8"><PageHeader title="Completar datos desde un documento" description="Obtén una propuesta de información a partir del contenido de un documento. Revisa los datos antes de utilizarlos." />
    <Card className="p-5 sm:p-6"><label htmlFor="analysis-mode" className="mb-2 block text-sm font-medium text-slate-800">¿Qué quieres extraer?</label><select id="analysis-mode" value={mode} onChange={(event) => { setMode(event.target.value as "organization" | "company"); setError(""); setOrganization(null); setCompany(null); }} className="h-11 w-full max-w-xs rounded-lg border border-slate-300 bg-white px-3 text-[15px] outline-none focus-visible:ring-4 focus-visible:ring-slate-900/10"><option value="organization">Datos de organización</option><option value="company">Perfil de empresa</option></select><form onSubmit={submit} className="mt-6">{mode === "organization" ? <><label htmlFor="document-content" className="mb-2 block text-sm font-medium text-slate-800">Contenido del documento</label><textarea id="document-content" required maxLength={MAX_DOCUMENT_LENGTH} value={text} onChange={(event) => setText(event.target.value)} className="min-h-64 w-full rounded-lg border border-slate-300 bg-white p-3 text-[15px] outline-none focus-visible:ring-4 focus-visible:ring-slate-900/10" placeholder="Pega aquí el texto del documento que deseas analizar..." /><p className="mt-2 text-xs text-slate-500">{text.length.toLocaleString("es-CL")} / {MAX_DOCUMENT_LENGTH.toLocaleString("es-CL")} caracteres</p></> : <><label htmlFor="company-pdf" className="mb-2 block text-sm font-medium text-slate-800">PDF societario con capa de texto</label><input id="company-pdf" type="file" accept="application/pdf" required onChange={(event) => setFile(event.target.files?.[0] ?? null)} className="block w-full text-sm text-slate-600" /><p className="mt-2 text-xs text-slate-500">Solo PDF, máximo 5 MB y 20 páginas. El archivo no se almacena.</p></>}<div className="mt-5 w-full sm:w-auto"><PrimaryButton type="submit" className="sm:w-auto" isLoading={loading} loadingLabel="Analizando…">Analizar documento</PrimaryButton></div></form></Card>
    {error && <div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800" role="alert">{error}</div>}
    {organization && <Card className="p-5 sm:p-6"><h2 className="font-semibold text-[#111c30]">Propuesta generada</h2><p className="mt-1 text-sm text-slate-600">Los datos son una propuesta generada automáticamente y deben ser revisados antes de utilizarlos.</p><div className="mt-6 grid gap-5 sm:grid-cols-2"><TextField id="proposal-organization" label="Nombre organización" defaultValue={organization.organization_name ?? ""} /><TextField id="proposal-rut" label="RUT" defaultValue={organization.rut ?? ""} /><div className="sm:col-span-2"><label htmlFor="proposal-activity" className="mb-2 block text-sm font-medium text-slate-800">Descripción de actividad</label><textarea id="proposal-activity" defaultValue={organization.activity_description ?? ""} className="min-h-28 w-full rounded-lg border border-slate-300 p-3" /></div></div><Warnings items={organization.warnings} /><button type="button" onClick={() => setOrganization(null)} className="mt-6 text-sm font-medium text-slate-700 underline">Descartar</button></Card>}
    {company && <Card className="p-5 sm:p-6"><h2 className="font-semibold text-[#111c30]">Datos detectados</h2><p className="mt-1 text-sm text-slate-600">Este contenido es una propuesta generada automáticamente y debe ser revisado antes de registrarlo.</p><form onSubmit={applyCompany} className="mt-6 grid gap-5 sm:grid-cols-2"><TextField id="company-name" name="name" label="Razón social" required defaultValue={company.legal_name ?? ""} /><TextField id="company-rut" name="rut" label="RUT" required defaultValue={company.rut ?? ""} /><div><label htmlFor="company-type" className="mb-2 block text-sm font-medium text-slate-800">Tipo societario</label><select id="company-type" name="company_type" defaultValue={company.company_type} className="h-11 w-full rounded-lg border border-slate-300 bg-white px-3"><option value="SPA">SpA</option><option value="LIMITADA">Limitada</option><option value="SA_CERRADA">S.A. Cerrada</option><option value="SA_ABIERTA">S.A. Abierta</option><option value="EIRL">EIRL</option><option value="OTHER">Otro</option><option value="UNKNOWN">No identificado</option></select></div><TextField id="company-address" name="address" label="Domicilio" defaultValue={company.address ?? ""} /><div className="sm:col-span-2"><label htmlFor="company-purpose" className="mb-2 block text-sm font-medium text-slate-800">Objeto o actividad principal</label><textarea id="company-purpose" name="business_purpose" defaultValue={company.business_purpose ?? ""} className="min-h-28 w-full rounded-lg border border-slate-300 p-3" /></div><div className="sm:col-span-2 rounded-lg bg-slate-50 p-4 text-sm text-slate-600"><p className="font-medium text-slate-800">Información no persistida</p><p className="mt-1">Representantes: {company.legal_representatives.join(", ") || "No detectados"}</p><p>Fecha del documento: {company.document_date ?? "No detectada"} · Fecha de constitución: {company.incorporation_date ?? "No detectada"}</p></div><div className="sm:col-span-2"><Warnings items={company.warnings} /></div><div className="flex gap-3"><PrimaryButton type="submit" className="w-auto" isLoading={saving} loadingLabel="Aplicando…">Aplicar al perfil</PrimaryButton><button type="button" onClick={() => setCompany(null)} className="text-sm font-medium text-slate-700 underline">Descartar</button></div></form></Card>}
  </div>}</DashboardGate>;
}

function Warnings({ items }: { items: string[] }) { return items.length ? <div className="mt-6 rounded-lg border border-amber-200 bg-amber-50 px-4 py-3"><p className="text-sm font-medium text-amber-900">Advertencias</p><ul className="mt-2 list-disc pl-5 text-sm text-amber-800">{items.map((item) => <li key={item}>{item}</li>)}</ul></div> : null; }
