"use client";

import { useEffect, useMemo, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { DashboardGate } from "@/components/auth/dashboard-gate";
import { PrimaryButton } from "@/components/ui/primary-button";
import { Card, EmptyState, PageHeader, StatusBadge } from "@/components/ui/surface";
import { CompliancePlanProposalCard } from "@/features/obligations/compliance-plan-proposal";
import { archiveObligation, createControl, createEvidence, generateCompliancePlan, getControls, getCurrentUser, getEvidences, getObligation, getUsers, type AuthenticatedUser, type CompliancePlanProposal, type Control, type Evidence, type Obligation, type OrganizationUser, updateControl, updateControlStatus, updateObligationStatus } from "@/lib/api";

const labels={PENDING:"Pendiente",IN_PROGRESS:"En proceso",COMPLIANT:"Cumplida",OVERDUE:"Vencida",COMPLETED:"Completado"};
const tones={PENDING:"neutral",IN_PROGRESS:"warning",COMPLIANT:"success",OVERDUE:"danger",COMPLETED:"success"} as const;

function Progress({controls}:{controls:Control[]}) { const summary=useMemo(()=>{const today=new Date().toISOString().slice(0,10), completed=controls.filter(x=>x.status==="COMPLETED").length, pending=controls.filter(x=>x.status!=="COMPLETED").length, overdue=controls.filter(x=>x.status!=="COMPLETED"&&!!x.due_date&&x.due_date<today).length;return {completed,pending,overdue,percentage:controls.length?Math.round(completed*100/controls.length):0};},[controls]); return <div className="mt-5 rounded-lg border border-slate-200 bg-slate-50 p-4"><div className="flex flex-wrap justify-between gap-2"><div><h3 className="font-semibold text-[#111c30]">Avance del plan</h3><p className="mt-1 text-sm text-slate-600">{summary.completed} de {controls.length} acciones completadas · {summary.percentage}%</p></div>{summary.overdue>0&&<span className="text-sm font-medium text-red-700">{summary.overdue} {summary.overdue===1?"acción vencida":"acciones vencidas"}</span>}</div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-[#111c30]" style={{width:`${summary.percentage}%`}} /></div>{summary.pending>0&&<p className="mt-2 text-xs text-slate-500">{summary.pending} acciones pendientes o en proceso</p>}</div> }

export default function ObligationDetailPage(){
 const {id}=useParams<{id:string}>(),router=useRouter(); const [obligation,setObligation]=useState<Obligation|null>(null),[user,setUser]=useState<AuthenticatedUser|null>(null),[users,setUsers]=useState<OrganizationUser[]>([]),[controls,setControls]=useState<Control[]>([]),[evidences,setEvidences]=useState<Evidence[]>([]),[error,setError]=useState(""),[feedback,setFeedback]=useState(""),[title,setTitle]=useState(""),[date,setDate]=useState(""),[proposal,setProposal]=useState<CompliancePlanProposal|null>(null),[generating,setGenerating]=useState(false),[editing,setEditing]=useState<Control|null>(null);
 const loadControls=async()=>setControls(await getControls(id));
 useEffect(()=>{Promise.all([getObligation(id),getCurrentUser(),getControls(id),getEvidences(id)]).then(([o,u,c,e])=>{setObligation(o);setUser(u);setControls(c);setEvidences(e);if(u.role==="ADMIN")getUsers().then(setUsers)}).catch(x=>setError(x instanceof Error?x.message:"No fue posible cargar la obligación."));},[id]);
 if(!obligation)return <DashboardGate>{error?<EmptyState title="No fue posible cargar la obligación" description={error}/>:<Card className="p-8" role="status">Cargando obligación…</Card>}</DashboardGate>;
 const canManage=user?.role==="ADMIN"||(user?.role==="RESPONSIBLE"&&obligation.responsible_user_id===user.id), userName=(userId:string|null)=>users.find(x=>x.id===userId)?.name??(userId?"Usuario asignado":"Sin asignar");
 async function addControl(e:React.FormEvent){e.preventDefault();try{const c=await createControl(id,{title,due_date:date||null});setControls(v=>[c,...v]);setTitle("");setDate("")}catch(x){setError(x instanceof Error?x.message:"No fue posible crear la acción.")}}
 async function generate(){setError("");setGenerating(true);try{setProposal(await generateCompliancePlan(id))}catch(x){setError(x instanceof Error?x.message:"No fue posible generar el plan.")}finally{setGenerating(false)}}
 return <DashboardGate><main className="mx-auto max-w-5xl space-y-8"><PageHeader title={obligation.title} description={`Obligación ambiental · ${obligation.matter}`} action={<div className="flex gap-3">{user?.role==="ADMIN"&&<button onClick={()=>{if(confirm("¿Archivar esta obligación?"))archiveObligation(id).then(()=>router.push("/obligations")).catch(()=>setError("No fue posible archivar."))}} className="rounded-lg border border-red-200 px-4 py-2 text-sm font-semibold text-red-700">Archivar</button>}</div>}/>
 <Card className="p-5 sm:p-6"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-xl font-semibold text-[#111c30]">Información</h2><StatusBadge tone={tones[obligation.compliance_status]}>{labels[obligation.compliance_status]}</StatusBadge></div><dl className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><div><dt className="text-sm text-slate-500">Materia</dt><dd>{obligation.matter}</dd></div><div><dt className="text-sm text-slate-500">Fuente normativa</dt><dd>{obligation.regulatory_source}</dd></div><div><dt className="text-sm text-slate-500">Responsable</dt><dd>{obligation.responsible_user?.name??"Sin asignar"}</dd></div><div><dt className="text-sm text-slate-500">Fecha límite</dt><dd>{obligation.deadline??"—"}</dd></div><div><dt className="text-sm text-slate-500">Periodicidad</dt><dd>{obligation.frequency??"—"}</dd></div></dl><p className="mt-5 border-t border-slate-100 pt-5 whitespace-pre-wrap text-slate-700">{obligation.description??"Sin descripción."}</p>{canManage&&<label className="mt-5 block text-sm text-slate-700">Estado<select className="ml-3 h-10 rounded-lg border border-slate-300 bg-white px-3" value={obligation.compliance_status} onChange={async e=>{try{setObligation(await updateObligationStatus(id,e.target.value as Obligation["compliance_status"]))}catch{setError("No fue posible actualizar el estado.")}}}>{["PENDING","IN_PROGRESS","COMPLIANT","OVERDUE"].map(status=><option key={status} value={status}>{labels[status as keyof typeof labels]}</option>)}</select></label>}</Card>
 <Card className="p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold text-[#111c30]">Acciones de cumplimiento</h2><p className="mt-1 text-sm text-slate-600">Acciones operativas para organizar la ejecución de esta obligación.</p></div>{user?.role==="ADMIN"&&<PrimaryButton type="button" onClick={generate} disabled={generating}>{generating?"Generando plan…":"Generar plan con IA"}</PrimaryButton>}</div><Progress controls={controls}/><div className="mt-5 space-y-3">{controls.map(control=>editing?.id===control.id?<ControlEditor key={control.id} control={control} users={users} admin={user?.role==="ADMIN"} onCancel={()=>setEditing(null)} onSaved={updated=>{setControls(v=>v.map(x=>x.id===updated.id?updated:x));setEditing(null)}} onError={setError}/>:<article key={control.id} className="flex flex-wrap items-start justify-between gap-3 rounded-lg border border-slate-200 p-4"><div><p className="font-medium text-slate-900">{control.title}</p>{control.description&&<p className="mt-1 text-sm text-slate-600">{control.description}</p>}<dl className="mt-3 grid gap-x-5 gap-y-1 text-sm sm:grid-cols-3"><div><dt className="text-slate-500">Responsable</dt><dd>{userName(control.responsible_user_id)}</dd></div><div><dt className="text-slate-500">Fecha objetivo</dt><dd>{control.due_date??"Sin fecha"}</dd></div><div><dt className="text-slate-500">Evidencia esperada</dt><dd>{control.expected_evidence??"No definida"}</dd></div></dl></div><div className="flex items-center gap-3"><StatusBadge tone={tones[control.status]}>{labels[control.status]}</StatusBadge>{canManage&&<><button onClick={()=>setEditing(control)} className="rounded-lg border border-slate-300 px-3 py-2 text-sm">Editar</button><select aria-label={`Estado de ${control.title}`} value={control.status} onChange={async e=>{try{const c=await updateControlStatus(control.id,e.target.value as Control["status"]);setControls(v=>v.map(x=>x.id===c.id?c:x))}catch{setError("No fue posible actualizar la acción.")}}} className="h-10 rounded-lg border border-slate-300 bg-white px-3 text-sm">{["PENDING","IN_PROGRESS","COMPLETED"].map(status=><option key={status}>{labels[status as keyof typeof labels]}</option>)}</select></>}</div></article>)}{controls.length===0&&<p className="rounded-lg bg-slate-50 p-4 text-sm text-slate-500">No hay acciones registradas.</p>}</div>{canManage&&<form onSubmit={addControl} className="mt-5 grid gap-3 sm:grid-cols-[1fr_auto_auto]"><input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Título de la acción" className="h-11 rounded-lg border border-slate-300 px-3"/><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="h-11 rounded-lg border border-slate-300 px-3"/><PrimaryButton>Agregar acción</PrimaryButton></form>}</Card>
 {proposal&&<CompliancePlanProposalCard obligationId={id} proposal={proposal} users={users} onDiscard={()=>setProposal(null)} onError={setError} onCreated={async()=>{await loadControls();setProposal(null);setFeedback("Las acciones seleccionadas fueron agregadas al plan.")}}/>}
 <Card className="p-5 sm:p-6"><h2 className="text-xl font-semibold text-[#111c30]">Evidencias registradas</h2><div className="mt-5 space-y-3">{evidences.map(e=><article key={e.id} className="rounded-lg border border-slate-200 p-4"><p className="font-medium">{e.name}</p>{e.external_url&&<a href={e.external_url} target="_blank" rel="noreferrer" className="mt-2 inline-block text-sm underline">Abrir enlace</a>}<p className="mt-2 text-xs text-slate-500">Registrada por {e.uploaded_by_user.name}</p></article>)}{evidences.length===0&&<p className="rounded-lg bg-slate-50 p-4 text-sm text-slate-500">No hay evidencias registradas.</p>}</div></Card>{feedback&&<p className="text-sm text-emerald-700">{feedback}</p>}{error&&<p className="text-sm text-red-700" role="alert">{error}</p>}</main></DashboardGate>;
}

function ControlEditor({control,users,admin,onCancel,onSaved,onError}:{control:Control;users:OrganizationUser[];admin:boolean;onCancel:()=>void;onSaved:(control:Control)=>void;onError:(message:string)=>void}){async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);try{onSaved(await updateControl(control.id,{title:data.get("title"),description:data.get("description")||null,due_date:data.get("due_date")||null,expected_evidence:data.get("expected_evidence")||null,...(admin?{responsible_user_id:data.get("responsible_user_id")||null}:{})}))}catch(x){onError(x instanceof Error?x.message:"No fue posible editar la acción.")}}return <form onSubmit={submit} className="grid gap-3 rounded-lg border border-slate-200 p-4"><input name="title" required defaultValue={control.title} className="h-10 rounded-lg border border-slate-300 px-3"/><textarea name="description" defaultValue={control.description??""} placeholder="Descripción" className="min-h-20 rounded-lg border border-slate-300 p-3"/><div className="grid gap-3 sm:grid-cols-3"><input name="due_date" type="date" defaultValue={control.due_date??""} className="h-10 rounded-lg border border-slate-300 px-3"/><input name="expected_evidence" defaultValue={control.expected_evidence??""} placeholder="Evidencia esperada" className="h-10 rounded-lg border border-slate-300 px-3"/>{admin&&<select name="responsible_user_id" defaultValue={control.responsible_user_id??""} className="h-10 rounded-lg border border-slate-300 bg-white px-3"><option value="">Sin asignar</option>{users.filter(u=>u.is_active&&(u.role==="ADMIN"||u.role==="RESPONSIBLE")).map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select>}</div><div className="flex gap-2"><PrimaryButton>Guardar</PrimaryButton><button type="button" onClick={onCancel} className="rounded-lg border border-slate-300 px-3">Cancelar</button></div></form>}
