"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { DashboardGate } from "@/components/auth/dashboard-gate";
import { Card, EmptyState, PageHeader, StatusBadge } from "@/components/ui/surface";
import { getCurrentUser, getObligations, type AuthenticatedUser, type Obligation } from "@/lib/api";

const labels = { PENDING: "Pendiente", IN_PROGRESS: "En proceso", COMPLIANT: "Cumplida", OVERDUE: "Vencida" };
const tone = { PENDING: "warning", IN_PROGRESS: "info", COMPLIANT: "success", OVERDUE: "danger" } as const;

export default function ObligationsPage() {
  const [items, setItems] = useState<Obligation[]>([]); const [user, setUser] = useState<AuthenticatedUser | null>(null); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [responsible, setResponsible] = useState(""); const [error, setError] = useState("");
  useEffect(() => { Promise.all([getObligations(), getCurrentUser()]).then(([obligations, currentUser]) => { setItems(obligations); setUser(currentUser); }).catch(() => setError("No fue posible cargar las obligaciones.")); }, []);
  const people = useMemo(() => [...new Map(items.filter((item) => item.responsible_user).map((item) => [item.responsible_user!.id, item.responsible_user!.name])).entries()], [items]);
  const filtered = items.filter((item) => (!search || item.title.toLowerCase().includes(search.toLowerCase())) && (!status || item.compliance_status === status) && (!responsible || item.responsible_user_id === responsible));
  return <DashboardGate><div className="space-y-6"><PageHeader title="Obligaciones" description="Gestiona las obligaciones ambientales de tu organización." action={user?.role === "ADMIN" ? <Link href="/obligations/new" className="rounded-lg bg-[#111c30] px-4 py-3 text-sm font-semibold text-white">Crear obligación</Link> : undefined} /><Card className="p-4"><div className="grid gap-3 md:grid-cols-3"><input className="h-11 rounded-lg border border-slate-300 bg-slate-50 px-3" placeholder="Buscar por título" value={search} onChange={(event) => setSearch(event.target.value)} /><select className="h-11 rounded-lg border border-slate-300 bg-slate-50 px-3" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Todos los estados</option>{Object.entries(labels).map(([value, itemLabel]) => <option key={value} value={value}>{itemLabel}</option>)}</select><select className="h-11 rounded-lg border border-slate-300 bg-slate-50 px-3" value={responsible} onChange={(event) => setResponsible(event.target.value)}><option value="">Todos los responsables</option>{people.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></div></Card>{error ? <p className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</p> : filtered.length === 0 ? <EmptyState title={items.length === 0 ? "Aún no hay obligaciones" : "No hay resultados"} description={items.length === 0 ? "Registra una obligación ambiental para comenzar el seguimiento." : "Prueba ajustando los filtros de búsqueda."} /> : <Card className="overflow-x-auto"><table className="min-w-[800px] w-full text-left text-sm"><thead className="border-b bg-slate-50 text-slate-500"><tr>{["Título", "Materia", "Fuente normativa", "Responsable", "Fecha límite", "Estado"].map((heading) => <th key={heading} className="px-5 py-4 font-semibold">{heading}</th>)}</tr></thead><tbody>{filtered.map((item) => <tr key={item.id} className="border-b border-slate-100 hover:bg-slate-50"><td className="px-5 py-4 font-medium text-[#111c30]"><Link href={`/obligations/${item.id}`}>{item.title}</Link></td><td className="px-5 py-4">{item.matter}</td><td className="px-5 py-4">{item.regulatory_source}</td><td className="px-5 py-4">{item.responsible_user?.name ?? "Sin asignar"}</td><td className="px-5 py-4">{item.deadline ?? "—"}</td><td className="px-5 py-4"><StatusBadge tone={tone[item.compliance_status]}>{labels[item.compliance_status]}</StatusBadge></td></tr>)}</tbody></table></Card>}</div></DashboardGate>;
}
