import Link from "next/link";
import { Card, StatusBadge } from "@/components/ui/surface";
import type { DashboardAttention, DashboardSummary } from "@/lib/api";

const labels = { COMPLIANT: "Cumplida", IN_PROGRESS: "En proceso", PENDING: "Pendiente", OVERDUE: "Vencida" };
const tones = { COMPLIANT: "success", IN_PROGRESS: "info", PENDING: "warning", OVERDUE: "danger" } as const;
const reasons = { OVERDUE: "Vencida", DUE_SOON: "Próxima a vencer", UNASSIGNED: "Sin responsable", PENDING: "Pendiente" };

export function AttentionPanel({ summary, items }: { summary: DashboardSummary; items: DashboardAttention[] }) {
  return <Card className="dashboard-panel overflow-hidden border-amber-100/80 bg-[var(--surface)]"><div className="border-b border-amber-100 bg-[#fff7e6] px-4 py-3.5 sm:px-5"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="text-lg font-semibold text-[#111c30]">Cumplimientos urgentes</h2><p className="mt-0.5 text-sm text-slate-600">Vencidas, próximas a vencer y sin responsable.</p></div><Link href="/obligations" className="text-sm font-medium text-[#172033] underline-offset-4 transition hover:text-[#4f86b7] hover:underline">Ver todas</Link></div><div className="mt-2.5 flex flex-wrap gap-2 text-xs font-medium"><span className="rounded-full bg-red-50 px-2.5 py-1 text-red-800">{summary.overdue} vencidas</span><span className="rounded-full bg-amber-50 px-2.5 py-1 text-amber-800">{summary.due_soon} próximas</span><span className="rounded-full bg-violet-50 px-2.5 py-1 text-violet-800">{summary.unassigned} sin responsable</span></div></div><div className="px-4 sm:px-5">{items.slice(0, 4).length ? items.slice(0, 4).map((item) => <Link key={item.id} href={`/obligations/${item.id}`} className="-mx-2 flex items-center justify-between gap-3 border-b border-slate-200/70 px-2 py-2.5 last:border-b-0 transition duration-200 hover:bg-[var(--surface-cool)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#111c30]/30"><span className="min-w-0"><b className="block truncate text-sm text-[#111c30]">{item.title}</b><span className="mt-0.5 block truncate text-xs text-slate-500">{item.responsible_name ?? "Sin responsable"} · {reasons[item.attention_reason]}</span></span><span className="shrink-0 text-right"><StatusBadge tone={tones[item.compliance_status]}>{labels[item.compliance_status]}</StatusBadge><small className="mt-1 block text-xs text-slate-500">{item.deadline ?? "Sin fecha"}</small></span></Link>) : <p className="py-5 text-sm text-slate-500">No hay obligaciones que requieran atención.</p>}</div></Card>;
}
