"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { DashboardGate } from "@/components/auth/dashboard-gate";
import { Card, PageHeader, StatusBadge } from "@/components/ui/surface";
import { KpiStrip } from "@/components/ui/kpi-strip";
import { AlertIcon, CheckCircleIcon, ClipboardIcon, ClockIcon, UsersIcon } from "@/components/ui/icons";
import { DashboardAmbientShader } from "@/components/ui/dashboard-ambient-shader";
import { getCurrentUser, getDashboardAttention, getDashboardSummary, getDashboardUpcoming, type AuthenticatedUser, type DashboardAttention, type DashboardObligation, type DashboardSummary } from "@/lib/api";

const label = { COMPLIANT: "Cumplida", IN_PROGRESS: "En proceso", PENDING: "Pendiente", OVERDUE: "Vencida" };
const tone = { COMPLIANT: "success", IN_PROGRESS: "info", PENDING: "warning", OVERDUE: "danger" } as const;

function ObligationList({ items, empty, showReason = false }: { items: (DashboardObligation | DashboardAttention)[]; empty: string; showReason?: boolean }) {
  const reasons = { OVERDUE: "Vencida", DUE_SOON: "Próxima a vencer", UNASSIGNED: "Sin responsable", PENDING: "Pendiente" };
  return <div className="divide-y divide-slate-100">{items.length ? items.map((item) => <Link key={item.id} href={`/obligations/${item.id}`} className="-mx-2 flex items-center justify-between gap-4 rounded-md px-2 py-4 transition duration-200 hover:bg-[var(--surface-muted)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#111c30]/30"><span><b className="block text-[15px] text-[#111c30]">{item.title}</b><span className="mt-0.5 block text-sm text-slate-500">Responsable: {item.responsible_name ?? "Sin responsable"}{showReason && "attention_reason" in item ? ` · ${reasons[item.attention_reason]}` : ""}</span></span><span className="shrink-0 text-right"><StatusBadge tone={tone[item.compliance_status]}>{label[item.compliance_status]}</StatusBadge><small className="mt-1 block text-[13px] text-slate-500">{item.deadline ?? "Sin fecha"}</small></span></Link>) : <p className="py-6 text-[15px] text-slate-500">{empty}</p>}</div>;
}

export default function DashboardPage() {
  const [summary, setSummary] = useState<DashboardSummary | null>(null);
  const [attention, setAttention] = useState<DashboardAttention[]>([]);
  const [upcoming, setUpcoming] = useState<DashboardObligation[]>([]);
  const [user, setUser] = useState<AuthenticatedUser | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { Promise.all([getDashboardSummary(), getDashboardAttention(), getDashboardUpcoming(), getCurrentUser()]).then(([loadedSummary, loadedAttention, loadedUpcoming, loadedUser]) => { setSummary(loadedSummary); setAttention(loadedAttention); setUpcoming(loadedUpcoming); setUser(loadedUser); }).catch(() => setError("No pudimos cargar el estado de cumplimiento.")); }, []);

  const hasObligations = Boolean(summary && summary.total_obligations > 0);
  return <DashboardGate><div className="relative isolate"><DashboardAmbientShader /><div className="relative z-10 space-y-8 motion-safe:animate-[dashboard-enter_220ms_ease-out]"><PageHeader title="Dashboard" description="Estado general del cumplimiento ambiental de tu organización." action={user?.role === "ADMIN" && hasObligations ? <Link className="inline-flex h-12 items-center justify-center rounded-lg bg-[#111c30] px-4 text-sm font-semibold text-white transition duration-200 hover:-translate-y-0.5 hover:bg-[#1a2943] hover:shadow-sm focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-slate-900/20" href="/obligations/new">Crear obligación</Link> : undefined} />
    {error && <p className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-[15px] text-red-700" role="alert">{error}</p>}
    {!summary && !error && <Card className="p-8 text-[15px] text-slate-500" role="status">Cargando resumen…</Card>}
    {summary && (summary.total_obligations === 0 ? <section className="mx-auto max-w-2xl pt-2 text-center sm:pt-4"><div className="mx-auto flex max-w-sm justify-center gap-8 border-y border-slate-200/80 py-5"><div><p className="text-3xl font-semibold text-[#111c30]">0</p><p className="mt-1 text-sm text-slate-500">Obligaciones</p></div><div className="h-10 w-px bg-slate-200" aria-hidden="true" /><div><p className="text-3xl font-semibold text-[#111c30]">—</p><p className="mt-1 text-sm text-slate-500">Cumplimiento</p></div></div><div className="pt-7"><h2 className="text-xl font-semibold text-[#111c30]">Comienza a gestionar tu cumplimiento</h2><p className="mx-auto mt-2 max-w-xl text-[15px] leading-6 text-slate-600">Registra tu primera obligación ambiental para comenzar a asignar responsables, controles y evidencias.</p>{user?.role === "ADMIN" && <Link className="mt-6 inline-flex h-12 items-center justify-center rounded-lg bg-[#111c30] px-4 text-sm font-semibold text-white transition duration-200 hover:-translate-y-0.5 hover:bg-[#1a2943] hover:shadow-sm focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-slate-900/20" href="/obligations/new">Crear primera obligación</Link>}</div></section> : <><KpiStrip metrics={[{ label: "Cumplimiento general", value: `${summary.compliance_percentage}%`, tone: "success", icon: CheckCircleIcon, featured: true, progress: summary.compliance_percentage, helper: `${summary.compliant} de ${summary.total_obligations} obligaciones cumplidas` }, { label: "Obligaciones vencidas", value: summary.overdue, tone: "danger", icon: AlertIcon }, { label: "Próximas a vencer", value: summary.due_soon, tone: "warning", icon: ClockIcon }, { label: "Obligaciones activas", value: summary.active, tone: "info", icon: ClipboardIcon }, { label: "Sin responsable", value: summary.unassigned, tone: "violet", icon: UsersIcon }]} />
      {summary.unassigned > 0 && <p className="rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800 shadow-sm">{summary.unassigned} obligaciones sin responsable requieren asignación.</p>}
      <div className="grid gap-6 xl:grid-cols-2"><Card className="dashboard-panel bg-[var(--surface-muted)] p-5 sm:p-6"><p className="text-sm font-medium text-slate-500">Distribución por estado</p><div className="mt-2 flex items-baseline gap-3"><b className="text-4xl text-[#111c30]">{summary.compliance_percentage}%</b><span className="text-sm text-slate-500">{summary.compliant} de {summary.total_obligations} cumplidas</span></div><div className="mt-4 flex h-2 overflow-hidden rounded bg-slate-200"><i className="bg-emerald-600" style={{width:`${summary.compliant*100/summary.total_obligations}%`}}/><i className="bg-amber-500" style={{width:`${summary.in_progress*100/summary.total_obligations}%`}}/><i className="bg-slate-400" style={{width:`${summary.pending*100/summary.total_obligations}%`}}/><i className="bg-red-500" style={{width:`${summary.overdue*100/summary.total_obligations}%`}}/></div><p className="mt-4 flex flex-wrap gap-x-4 gap-y-2 text-sm text-slate-600"><span>Cumplidas {summary.compliant}</span><span>En proceso {summary.in_progress}</span><span>Pendientes {summary.pending}</span><span>Vencidas {summary.overdue}</span></p></Card><Card className="dashboard-panel p-5 sm:p-6"><h2 className="text-lg font-semibold text-[#111c30]">Próximos vencimientos</h2><ObligationList items={upcoming} empty="No hay próximos vencimientos." /></Card></div>
      <div className="grid gap-6 xl:grid-cols-2"><Card className="dashboard-panel bg-[var(--surface-muted)] p-5 sm:p-6"><p className="text-sm font-medium text-slate-500">Estado de cumplimiento</p><div className="mt-2 flex items-baseline gap-3"><b className="text-4xl text-[#111c30]">{summary.compliance_percentage}%</b><span className="text-sm text-slate-500">{summary.compliant} de {summary.total_obligations} cumplidas</span></div><div className="mt-4 flex h-2 overflow-hidden rounded bg-slate-200"><i className="bg-emerald-600" style={{width:`${summary.compliant*100/summary.total_obligations}%`}}/><i className="bg-amber-500" style={{width:`${summary.in_progress*100/summary.total_obligations}%`}}/><i className="bg-slate-400" style={{width:`${summary.pending*100/summary.total_obligations}%`}}/><i className="bg-red-500" style={{width:`${summary.overdue*100/summary.total_obligations}%`}}/></div><p className="mt-4 flex flex-wrap gap-x-4 gap-y-2 text-sm text-slate-600"><span>Cumplidas {summary.compliant}</span><span>En proceso {summary.in_progress}</span><span>Pendientes {summary.pending}</span><span>Vencidas {summary.overdue}</span></p></Card><Card className="dashboard-panel p-5 sm:p-6"><h2 className="text-lg font-semibold text-[#111c30]">Próximos vencimientos</h2><ObligationList items={upcoming} empty="No hay próximos vencimientos." /></Card></div>
      <Card className="dashboard-panel p-5 sm:p-6"><h2 className="text-lg font-semibold text-[#111c30]">Requieren atención</h2><ObligationList items={attention} showReason empty="No hay obligaciones que requieran atención." /></Card>
    </>)}
  </div></div></DashboardGate>;
}
